server.port=8091
spring.application.name=deal-service
spring.datasource.url=jdbc:h2:mem:dealservicedb
spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=false
spring.jpa.show-sql=false
spring.h2.console.enabled=true
