server.port=8090
spring.application.name=api-gateway
spring.flyway.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
services.deal.url=http://localhost:8091
services.plan.url=http://localhost:8092
services.calculation.url=http://localhost:8093
services.dispute.url=http://localhost:8094
